version: "1.0.1"

name: mytodoapp

services:
  api:
    build:
      context: ./todo_app
      dockerfile: Dockerfile
    depends_on:
        - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    networks:
      - my-api-net
  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
        - POSTGRES_USER=usman
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=todosdb
    ports:
        - '5432:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net

volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network